servies:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: social-nginx
    ports:
      - 8080:80
      - 444:443
    volumes:
      # - ./static:/usr/share/nginx/html:ro
      # - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    networks:
      - social

networks:
  social:
    external: true
